### ISSUE TITLE
Bug : program is shutting down if we try to create more than 1 ToDoList

### ISSUE THREAD

**Issue by mohithvinayak** [SHAY2407/ToDoList#11]
After we create a ToDo List using create your ToDo List  if we again use the create your ToDoList option the program is shutting down with out any response

**Comment by AryanGitHub** [comment]
yes, it's not crashing, but there should be no option of "Create a todo List "once it's created.

**Comment by AryanGitHub** [comment]
we have to modify the mainMenu() function and to check if the list is created or not if it's not then only Create a todoList list should be available

**Comment by AryanGitHub** [comment]
I fixed this bug, will publish it in my pull request.
