### ISSUE TITLE
Bug : If we try to delete a ToDo List without even creating one it is asking us to enter the number which you want to delete

### ISSUE THREAD

**Issue by mohithvinayak** [SHAY2407/ToDoList#12]
If we try to delete a ToDo List without even creating one it is asking us to enter the number which you want to delete and if we 
enter a number the program in shutting down . where it should have said Empty list or you don't have a ToDo List.

**Comment by AryanGitHub** [comment]
yes, also providing random number as input, the program crash.

**Comment by AryanGitHub** [comment]
I guess the way we can fix this bug is checking if there is a list already or not, if there is no list then it should print "Cannot delete as there is no list."

**Comment by AryanGitHub** [comment]
I fixed it, will share the pull request today.
